"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, Loader2 } from "lucide-react";
import Link from "next/link";
import { signIn, confirmSignIn, getCurrentUser } from "aws-amplify/auth";
import { useRouter } from "next/navigation";

const fadeUpVariant = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.8, ease: "easeInOut" } }
};

export default function Login() {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [mfaCode, setMfaCode] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");
  const [authStep, setAuthStep] = useState("SIGN_IN"); // SIGN_IN | CONFIRM_MFA

  const handleStandardLogin = async (e) => {
    e.preventDefault();
    setIsLoading(true);
    setErrorMsg("");

    try {
      const response = await signIn({
        username: email,
        password,
      });

      console.log("Cognito signIn response:", response);
      const { isSignedIn, nextStep } = response;

      if (isSignedIn) {
        console.log("User is signed in. Redirecting to /analyze...");
        const { userId, username } = await getCurrentUser();
        router.push(`/analyze/${userId || username || "me"}`);
      } else if (nextStep?.signInStep === "CONFIRM_SIGN_IN_WITH_TOTP" || nextStep?.signInStep === "CONFIRM_SIGN_IN_WITH_SMS_MFA") {
        setAuthStep("CONFIRM_MFA");
      } else {
        // Unhandled step
        console.warn("Unhandled nextStep:", nextStep);
        setErrorMsg(`Login requires further action: ${nextStep?.signInStep}`);
      }
    } catch (error) {
      console.error("Login error:", error);
      setErrorMsg(error.message || "An error occurred during sign in.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleMfaConfirm = async (e) => {
    e.preventDefault();
    setIsLoading(true);
    setErrorMsg("");

    try {
      const { isSignedIn } = await confirmSignIn({
        challengeResponse: mfaCode
      });
      if (isSignedIn) {
        const { userId, username } = await getCurrentUser();
        router.push(`/analyze/${userId || username || "me"}`);
      }
    } catch (error) {
      console.error("MFA confirm error:", error);
      setErrorMsg(error.message || "Invalid MFA code.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <main className="min-h-screen bg-white text-gray-900 selection:bg-indigo-100 selection:text-indigo-900 overflow-hidden font-sans relative flex items-center justify-center">

      {/* Exact Sarvam replica background gradient from Hero Section */}
      <div className="absolute top-0 inset-x-0 h-[800px] overflow-hidden pointer-events-none flex justify-center z-0">
        <div className="absolute top-[-10%] w-[150vw] max-w-[2500px] h-[800px] opacity-80 blur-[60px]" style={{ background: 'radial-gradient(50% 100% at 50% 0%, #D4C3FF 0%, rgba(212,195,255,0) 100%)' }}></div>
        <div className="absolute top-[-5%] w-[100vw] max-w-[1500px] h-[500px] opacity-90 blur-[80px]" style={{ background: 'radial-gradient(50% 100% at 50% 0%, #FFB472 0%, rgba(255,180,114,0) 100%)' }}></div>
      </div>

      <motion.div initial="hidden" animate="visible" variants={fadeUpVariant} className="w-full max-w-[480px] px-6 relative z-10">
        <div className="bg-white/70 backdrop-blur-xl border border-white/50 shadow-[0_8px_40px_rgb(0,0,0,0.08)] rounded-[2.5rem] p-8 w-full aspect-square flex flex-col justify-center mx-auto relative overflow-hidden">

          <div className="text-center mb-5">
            <h1 className="text-2xl font-serif font-medium text-gray-900 mb-1">
              {authStep === "SIGN_IN" ? "Welcome Back" : "Two-Factor Auth"}
            </h1>
            <p className="text-gray-500">
              {authStep === "SIGN_IN" ? "Sign in to Social Lens to continue" : "Enter the code generated by your app"}
            </p>
          </div>

          {errorMsg && (
            <div className="mb-4 p-3 bg-red-50 border border-red-100 text-red-600 text-sm rounded-xl text-center">
              {errorMsg}
            </div>
          )}

          {authStep === "SIGN_IN" ? (
            <>
              <form className="space-y-4" onSubmit={handleStandardLogin}>
                <div>
                  <label className="block text-[15px] font-serif font-medium text-gray-900 mb-1.5">Email</label>
                  <input
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="you@company.com"
                    className="w-full px-4 py-3 rounded-xl border border-gray-200 bg-white/60 focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-400 transition-all text-gray-900 placeholder:text-gray-400"
                    required
                  />
                </div>
                <div>
                  <div className="flex justify-between items-center mb-1.5">
                    <label className="block text-[15px] font-serif font-medium text-gray-900">Password</label>
                    <Link href="#" className="text-sm text-indigo-600 hover:text-indigo-700 font-medium transition-colors">
                      Forgot?
                    </Link>
                  </div>
                  <input
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="••••••••"
                    className="w-full px-4 py-3 rounded-xl border border-gray-200 bg-white/60 focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-400 transition-all text-gray-900 placeholder:text-gray-400"
                    required
                  />
                </div>

                <button type="submit" disabled={isLoading} className="w-full mt-4 group relative flex items-center justify-center gap-3 px-8 py-3.5 bg-gray-950 text-white rounded-xl font-medium text-base overflow-hidden transition-all shadow-xl hover:shadow-2xl disabled:opacity-75">
                  <div className="absolute inset-0 bg-gradient-to-r from-[#4A54A6] via-[#A8A1E2] to-[#E5B56D] opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                  <span className="relative z-10 flex items-center gap-2">
                    {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : <>Log In <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" /></>}
                  </span>
                </button>
              </form>

              <p className="mt-5 text-center text-sm text-gray-500">
                Don't have an account? <Link href="/signup" className="font-medium text-gray-900 hover:text-indigo-600 transition-colors">Sign up</Link>
              </p>
            </>
          ) : (
            <form className="space-y-4" onSubmit={handleMfaConfirm}>
              <div className="mt-4">
                <label className="block text-[15px] font-serif font-medium text-gray-900 mb-1.5 text-center">Authentication Code</label>
                <input
                  type="text"
                  value={mfaCode}
                  onChange={(e) => setMfaCode(e.target.value)}
                  placeholder="000000"
                  className="w-full px-4 py-3 text-center tracking-[0.5em] font-mono text-xl rounded-xl border border-gray-200 bg-white/60 focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-400 transition-all text-gray-900"
                  required
                  maxLength={6}
                />
              </div>

              <button type="submit" disabled={isLoading} className="w-full mt-6 group relative flex items-center justify-center gap-3 px-8 py-3.5 bg-gray-950 text-white rounded-xl font-medium text-base overflow-hidden transition-all shadow-xl hover:shadow-2xl disabled:opacity-75">
                <div className="absolute inset-0 bg-gradient-to-r from-[#4A54A6] via-[#A8A1E2] to-[#E5B56D] opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                <span className="relative z-10 flex items-center gap-2">
                  {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : <>Verify Identity <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" /></>}
                </span>
              </button>

              <button type="button" onClick={() => setAuthStep("SIGN_IN")} className="w-full mt-2 text-sm text-gray-500 hover:text-gray-800 transition-colors">
                Cancel
              </button>
            </form>
          )}

        </div>
      </motion.div>
    </main>
  );
}
